# PostgreSQL.(replaced MySQL) Versions 8.2 and up are supported.
# MySQL.  Versions 5.0+ are recommended.
# 
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= Rails.application.secrets[:database][:host] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  pool: 5

development:
  <<: *default
  database: <%= Rails.application.secrets[:database][:name] %>

test:
  <<: *default
  database: <%= Rails.application.secrets[:database][:name] %>

production:
  <<: *default
  secret_key_base: <%= ENV['DB_SECRET'] %>
  # host: <%= ENV['DB_SECRET'] %>
  # database: <%= ENV['DBNAME'] %>
  # username: <%= ENV['DBUSERNAME'] %>
  # password: <%= ENV['DBPASSWORD'] %>
  host: 129.194.70.52
  database: iotlabbackendlulea_production
  username: iotlabadministrator
  password: <%= ENV['RAILSEARCHER_DATABASE_PASSWORD'] %>
#production: *default


#
#   production:
#
