# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d61ca155ef2dfd9e4da54ab021171289ebde13906cd1d5c74cf9659cdbb2e3c26e5cbde63f4fa8d776de67a8e97a82ea773cbab061b38097e48522854d85f1e7
  database:
    # :host: localhost
    :name: iotlabbackendlulea_development
    :username: root
    :password: alisql

# add database section to all envs...

test:
  secret_key_base: 8e095e3faed5dfaf922e532209aa4ad1c5396145b578e0b35ca044018d5deec1e03c4e784d37bfb311ca1f7bf46362cf4944b50d462528ef7b56178af4bbbe87
  database:
    :host: localhost
    :name: iotlabbackendlulea_test
    :username: root
    :password: alisql

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7f0ce8a9416583586e69e93253234b6364424b6e10e8a3b60b4e3e1315bed234c0a569273a0778b9feb2f2aa2ebf4fa0b4644520eb0aa0dc2d42a8190406ebed
  database:
    :host: localhost
    :name: iotlabbackendlulea_production
    :username: root
    :password: alisql
